### ISSUE TITLE
Routine dependencies

### ISSUE THREAD

**Issue by bergel** [dspinellis/GW-BASIC#2]
I could not resist to visualize the dependencies between routines contained in the assembly source code files. Here is the result I have so far.

<img width="617" alt="Screen Shot 2020-05-23 at 17 31 26" src="https://user-images.githubusercontent.com/393742/82741204-d4eaee00-9d1d-11ea-9364-78f6daffbdba.png">
<img width="769" alt="Screen Shot 2020-05-23 at 17 29 40" src="https://user-images.githubusercontent.com/393742/82741206-d74d4800-9d1d-11ea-9f89-730bac01a46e.png">

**Comment by dspinellis** [comment]
Beautiful! Would you like to add with a pull request a reference to your work in the README file?

**Comment by bergel** [comment]
Done! Sorry to take so long to reply. Was very busy lately.
