### ISSUE TITLE
Add OEM.ASM file

### ISSUE THREAD

**Issue by sgros** [dspinellis/GW-BASIC#3]
I think that all the missing functions have to be recreated by reverse engineering, either source or GW BASIC binary. I assume documentation for interrupts (e.g. INT 10H that is used for screen handling) could also be useful input.

I created OEM.ASM file that allows everything to link, though there's still an 

https://gist.github.com/sgros/17b75aa895d3599b40ff5461cc9cccfe

I tried to implement SCROUT with an idea that this is minimall requirement to have GWBASIC binary to output something when started.

**Comment by dspinellis** [comment]
Nice!  Would you like to supply the file through a pull request?  I agree that INT 10h (rather than INT 21h) is the right abstraction level for these routines. For example, `SCROLL` is probably INT 10h —Function 06h.

**Comment by sgros** [comment]
I created pull request, hopefully right.

**Comment by dspinellis** [comment]
See also issue #4.
