### ISSUE TITLE
Some missing routines present in MS-DOS v1.25 BASICA.COM

### ISSUE THREAD

**Issue by tkchia** [dspinellis/GW-BASIC#4]
Hello @dspinellis,

Regarding the missing routines in the current GW-BASIC source release, it seems that at least some of them are actually present --- in binary form --- in [Microsoft's earlier MIT-licensed release of MS-DOS 1.25](https://github.com/microsoft/MS-DOS), specifically in `BASICA.COM`.  For example:
```
RAMTEXT:2279                   SETC            proc near       ; CODE XREF: CPLOT+74↑p
RAMTEXT:2279 8C C6                             mov     si, es
RAMTEXT:227B BF 00 B8                          mov     di, 0B800h
RAMTEXT:227E 8E C7                             mov     es, di
RAMTEXT:2280                                   assume es:nothing
RAMTEXT:2280 8B 1E F3 06                       mov     bx, word_14913
RAMTEXT:2284 26 8A 07                          mov     al, es:[bx]
RAMTEXT:2287 32 06 F6 06                       xor     al, byte_14916
RAMTEXT:228B 22 06 F5 06                       and     al, byte_14915
RAMTEXT:228F 26 30 07                          xor     es:[bx], al
RAMTEXT:2292 8E C6                             mov     es, si
RAMTEXT:2294                                   assume es:nothing
RAMTEXT:2294 C3                                retn
RAMTEXT:2294                   SETC            endp
```

However, I suspect that some of the missing routines might not be in this version of `BASICA.COM`, since `BASICA.COM` needs the original PC's ROM BASIC to run.

I hope this will be useful in some way.  Thank you!

**Comment by dspinellis** [comment]
Very useful idea, we could copy them from there!  

I went through all routine names and only found two matches.
```
for i in CLREOL CLRSCN CSRATR CSRDSP DONOTE DOWNC EDTMAP FETCHC FKYADV FKYFMT GETFBC GETHED GRPSIZ GTASPC GWINI GWTERM INFMAP INICOM INKMAP KEYINP LCPY LEFTC MAPSUP MAPXYC NREAD NSETCX NWRITE PEKFLT PGINIT PIXSIZ PNTINI POKFLT POLLEV PRTMAP RDPEN RDSTIK RDTRIG READC RECCOM RIGHTC SCALXY SCANL SCANR SCRATR SCRINP SCROLL SCROUT SCRSTT SEGINI SETATR SETC SETCBF SETCLR SETFBC SNDCOM SNDLPT STACOM STOREC SWIDTH TDOWNC TRMCOM TUPC UPC ; do
> git grep -w $i
> done
v2.0/source/DEBASM.ASM:GRPSIZ: MOV     BYTE PTR [DI],2
v1.25/source/COMMAND.ASM:        JZ      SCROLL          ;If not, just continue
v1.25/source/COMMAND.ASM:        JNZ     SCROLL
v1.25/source/COMMAND.ASM:SCROLL:
v1.25/source/COMMAND.ASM:        JMP     SHORT SCROLL
v2.0/source/TCODE4.ASM:        JZ      SCROLL          ; If not, just continue
v2.0/source/TCODE4.ASM:        JNZ     SCROLL
v2.0/source/TCODE4.ASM:SCROLL:
v2.0/source/TCODE4.ASM:        JMP     SHORT SCROLL
```

Where and how did you find `SETC`?  Do you want to issue a pull request for it?

**Comment by tkchia** [comment]
Hello @dspinellis,

> Where and how did you find `SETC`?

It is in `v1.25/bin/BASICA.COM`.  For some reason, Microsoft released this only in binary form.  I used a disassembler (IDA Freeware 5.0) to disassemble `BASICA.COM` and tried to match the binary code and data structures against the (newer) GW-BASIC source code.  Many of the data structures, e.g. `ALPTAX`, were pretty much identical across the two.

> Do you want to issue a pull request for it?

Yes, I hope to do that soon.

Thank you!

**Comment by dspinellis** [comment]
Oh, I see.  And by matching the call sites you can identify the targets we're missing. Very clever!

**Comment by lpereira** [comment]
Some of the missing routines are part of the MSX BIOS routines.  (MSX was a computer that came with MS-BASIC in the ROM and the BIOS was designed by MS.)  For instance, the `STOREC` routine is part of the MSX BIOS.  It's very different that what it would be on a PC, however, given that there's no documentation, that match serve as at least a hint on what they're supposed to do.  Here's a list of all BIOS routines: http://map.grauw.nl/resources/msxbios.php

I noticed this because I'm writing a program to convert this code back to Z80 so I can use GW-BASIC on a MSX.  The converter is in my repository, and I noticed that there has been some nice activity on other forks.  I'll need some help getting everything working there, and I'm keeping an eye on this repo :D

**Comment by dspinellis** [comment]
Very good point!  I run a join between the GWBASIC missing routines and the MSX BIOS routines, and the following are common.  We can, at least, understand their specification from there. I see that they concern the graphics system. Consequently, a text-only first implementation would work without them.
```
DOWNC
FETCHC
GTASPC
LEFTC
NSETCX
PNTINI
READC
RIGHTC
SCALXY
SCANL
SCANR
SETATR
SETC
STOREC
TDOWNC
TUPC
UPC
```

**Comment by buricco** [comment]
Would a binary of 2.01 or 2.02 be of any sort of use?

**Comment by tkchia** [comment]
@buricco: as far as I know Microsoft has not released other versions of Microsoft BASIC (or even the ROM BASIC portion needed by v1.25 `BASICA.COM`) under any open source license, so it might be tricky to make use of these other BASICs.  But I hope I am wrong. :-)
